//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 210.149954 on Stable branch
// Generated with ALiVE version 1.17.0.2209061
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_HesetSemi_Organized {
        displayName = "[10th] Heset Semi-Organized";
        side = 0;
        flag = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        icon = "\OPTRE_Core\Data\flag_Ins_ca.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_HesetSemi_Organized {
            name = "[10th] Heset Semi-Organized";

            class Infantry {
                name = "Infantry";

                class o_hesetsemi_organized_infantry_patrol {
                    name = "Patrol";
                    side = 0;
                    faction = "O_HesetSemi_Organized";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Riflemen_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_RTO_01";
                    };
                };

                class o_hesetsemi_organized_infantry_squad {
                    name = "Squad";
                    side = 0;
                    faction = "O_HesetSemi_Organized";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Riflemen_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Medic_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Riflemen_01";
                    };
                    class Unit4 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Riflemen_01";
                    };
                    class Unit5 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Riflemen_01";
                    };
                    class Unit6 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Riflemen_01";
                    };
                    class Unit7 {
                        position[] = {-15,-25,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_RTO_01";
                    };
                };

                class o_hesetsemi_organized_infantry_at_squad {
                    name = "AT Squad";
                    side = 0;
                    faction = "O_HesetSemi_Organized";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_AT_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_AT_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_AT_01";
                    };
                };

                class o_hesetsemi_organized_infantry_aa_squad {
                    name = "AA Squad";
                    side = 0;
                    faction = "O_HesetSemi_Organized";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_AA_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_AA_01";
                    };
                };

                class o_hesetsemi_organized_infantry_marksmen_squad {
                    name = "Marksmen Squad";
                    side = 0;
                    faction = "O_HesetSemi_Organized";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_Squad_Marksmen_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_HesetSemi_Organized_RTO_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_Soldier_F;
    class O_Soldier_F_OCimport_01 : O_Soldier_F { scope = 0; class EventHandlers; };
    class O_Soldier_F_OCimport_02 : O_Soldier_F_OCimport_01 { class EventHandlers; };


    class O_HesetSemi_Organized_Squad_Lead_01 : O_Soldier_F_OCimport_02 {
        author = "HMC. A. ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Lead";
        side = 0;
        faction = "O_HesetSemi_Organized";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_UNSC_Army_Uniform_S_OLITRO";

        linkedItems[] = {"V_SmershVest_01_F","TCF_BERET_URA","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"V_SmershVest_01_F","TCF_BERET_URA","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"TCF_M14","OPTRE_M6B","OPTRE_Binoculars"};
        respawnWeapons[] = {"TCF_M14","OPTRE_M6B","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "B_AssaultPack_khk";

        ALiVE_orbatCreator_loadout[] = {{"TCF_M14","","","REC_HOLO_Red",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{"OPTRE_M6B","","OPTRE_M6G_Flashlight","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_UNSC_Army_Uniform_S_OLITRO",{{"MiniGrenade",2,1}}},{"V_SmershVest_01_F",{{"ACE_elasticBandage",10},{"ACE_packingBandage",10}}},{"B_AssaultPack_khk",{{"OPTRE_15Rnd_762x51_Mag",14,15}}},"TCF_BERET_URA","G_Aviator",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_HesetSemi_Organized_Medic_01 : O_Soldier_F_OCimport_02 {
        author = "HMC. A. ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "O_HesetSemi_Organized";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_rolled_surplus_crimson";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","Koslovich_Black_beret","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","Koslovich_Black_beret","ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter"};

        weapons[] = {"Tenthed_M7","OPTRE_M6B"};
        respawnWeapons[] = {"Tenthed_M7","OPTRE_M6B"};

        magazines[] = {"Tenthed_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag","Tenthed_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"Tenthed_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag","Tenthed_60Rnd_5x23mm_Mag_tracer","OPTRE_8Rnd_127x40_Mag"};

        backpack = "TCF_RUCKSACK_UNSC_BLK_MED_F";

        ALiVE_orbatCreator_loadout[] = {{"Tenthed_M7","","","OPTRE_M12_Optic",{"Tenthed_60Rnd_5x23mm_Mag_tracer",60},{},""},{},{"OPTRE_M6B","","OPTRE_M6G_Flashlight","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_Ins_ER_rolled_surplus_crimson",{}},{"LM_OPCAN_ACTV_CGC_VEST",{{"Tenthed_60Rnd_5x23mm_Mag",12,60}}},{"TCF_RUCKSACK_UNSC_BLK_MED_F",{{"ACE_elasticBandage",20},{"ACE_packingBandage",20},{"ACE_bloodIV_500",7},{"ACE_bloodIV_250",10},{"ACE_bloodIV",2},{"OPTRE_Biofoam",4},{"ACE_epinephrine",6},{"ACE_morphine",6},{"ACE_splint",4},{"ACE_tourniquet",4},{"ACE_surgicalKit",1}}},"Koslovich_Black_beret","",{},{"ItemMap","ItemGPS","TFAR_anprc152","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_HesetSemi_Organized_Riflemen_01 : O_Soldier_F_OCimport_02 {
        author = "HMC. A. ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Riflemen";
        side = 0;
        faction = "O_HesetSemi_Organized";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGod";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","OPTRE_UNSC_Watchcap","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","OPTRE_UNSC_Watchcap","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};

        weapons[] = {"OPTRE_BR55","OPTRE_M6B","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_BR55","OPTRE_M6B","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag","OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag","OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR55","","","OPTRE_M7_Sight",{"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",36},{},""},{},{"OPTRE_M6B","","OPTRE_M6G_Flashlight","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_Ins_ER_uniform_GGod",{}},{"LM_OPCAN_ACTV_CGC_VEST",{}},{"OPTRE_UNSC_Rucksack",{{"ACE_elasticBandage",8},{"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",17,36}}},"OPTRE_UNSC_Watchcap","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_HesetSemi_Organized_Sniper_01 : O_HesetSemi_Organized_Riflemen_01 {
        author = "HMC. A. ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "O_HesetSemi_Organized";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGod";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","OPTRE_UNSC_PatrolCap_Marines","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","OPTRE_UNSC_PatrolCap_Marines","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};

        weapons[] = {"OPTRE_SRS99D","OPTRE_M6B","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_SRS99D","OPTRE_M6B","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_4Rnd_145x114_APFSDS_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_SRS99D","","","OPTRE_SRS99C_Scope",{"OPTRE_4Rnd_145x114_APFSDS_Mag",4},{},""},{},{"OPTRE_M6B","","OPTRE_M6G_Flashlight","TCF_MA1B_AmmoCounter",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_Ins_ER_uniform_GGod",{{"OPTRE_4Rnd_145x114_APFSDS_Mag",2,4}}},{"LM_OPCAN_ACTV_CGC_VEST",{{"OPTRE_4Rnd_145x114_APFSDS_Mag",1,4}}},{"OPTRE_UNSC_Rucksack",{{"TCF_4Rnd_145x114_Mag_SST",8,4}}},"OPTRE_UNSC_PatrolCap_Marines","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_HesetSemi_Organized_AT_01 : O_HesetSemi_Organized_Riflemen_01 {
        author = "HMC. A. ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "AT";
        side = 0;
        faction = "O_HesetSemi_Organized";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGod";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Cap_marshal","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Cap_marshal","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};

        weapons[] = {"OPTRE_BR55","TCF_M41_SSR","OPTRE_M6B","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_BR55","TCF_M41_SSR","OPTRE_M6B","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_M41_Twin_HEAT","OPTRE_8Rnd_127x40_Mag","OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_M41_Twin_HEAT","OPTRE_8Rnd_127x40_Mag","OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR55","","","OPTRE_M7_Sight",{"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",36},{},""},{"TCF_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{"OPTRE_M6B","","OPTRE_M6G_Flashlight","TCF_MA1B_AmmoCounter",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_Ins_ER_uniform_GGod",{}},{"LM_OPCAN_ACTV_CGC_VEST",{{"ACE_elasticBandage",6},{"ACE_EntrenchingTool",1},{"OPTRE_36Rnd_95x40_Mag",14,36}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"OPTRE_M41_Twin_HEAT",4,2}}},"H_Cap_marshal","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_HesetSemi_Organized_AA_01 : O_HesetSemi_Organized_AT_01 {
        author = "HMC. A. ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA";
        side = 0;
        faction = "O_HesetSemi_Organized";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGod";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Cap_marshal","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Cap_marshal","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};

        weapons[] = {"OPTRE_BR55","launch_I_Titan_F","OPTRE_M6B","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_BR55","launch_I_Titan_F","OPTRE_M6B","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","Titan_AA","OPTRE_8Rnd_127x40_Mag","OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","Titan_AA","OPTRE_8Rnd_127x40_Mag","OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR55","","","OPTRE_M7_Sight",{"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",36},{},""},{"launch_I_Titan_F","","","",{"Titan_AA",1},{},""},{"OPTRE_M6B","","OPTRE_M6G_Flashlight","TCF_MA1B_AmmoCounter",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_Ins_ER_uniform_GGod",{}},{"LM_OPCAN_ACTV_CGC_VEST",{{"ACE_elasticBandage",8},{"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",12,36}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"Titan_AA",4,1}}},"H_Cap_marshal","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_HesetSemi_Organized_Squad_Marksmen_01 : O_HesetSemi_Organized_Squad_Lead_01 {
        author = "HMC. A. ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Marksmen";
        side = 0;
        faction = "O_HesetSemi_Organized";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_UNSC_Army_Uniform_R_TRO";

        linkedItems[] = {"OPCAN_CGAVest_B","H_Booniehat_mgrn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"OPCAN_CGAVest_B","H_Booniehat_mgrn","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};

        weapons[] = {"TCF_M14","OPTRE_M6B","OPTRE_Binoculars"};
        respawnWeapons[] = {"TCF_M14","OPTRE_M6B","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_15Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Backpack";

        ALiVE_orbatCreator_loadout[] = {{"TCF_M14","","","OPTRE_BR45_Scope",{"OPTRE_15Rnd_762x51_Mag",15},{},""},{},{"OPTRE_M6B","","OPTRE_M6G_Flashlight","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_UNSC_Army_Uniform_R_TRO",{}},{"OPCAN_CGAVest_B",{}},{"OPTRE_UNSC_Backpack",{{"ACE_elasticBandage",8},{"ACE_EntrenchingTool",1},{"OPTRE_15Rnd_762x51_Mag",18,15}}},"H_Booniehat_mgrn","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_HesetSemi_Organized_RTO_01 : O_HesetSemi_Organized_Riflemen_01 {
        author = "HMC. A. ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "RTO";
        side = 0;
        faction = "O_HesetSemi_Organized";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGod";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Cap_headphones","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Cap_headphones","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};

        weapons[] = {"TCF_ICWSX","OPTRE_M6B","OPTRE_Binoculars"};
        respawnWeapons[] = {"TCF_ICWSX","OPTRE_M6B","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag","OPTRE_32Rnd_762x51_Mag","OPTRE_8Rnd_127x40_Mag"};

        backpack = "B_RadioBag_01_ghex_F";

        ALiVE_orbatCreator_loadout[] = {{"TCF_ICWSX","","","OPTRE_HMG38_CarryHandle",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_M6B","","OPTRE_M6G_Flashlight","",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_Ins_ER_uniform_GGod",{{"ACE_elasticBandage",5},{"OPTRE_32Rnd_762x51_Mag",3,32}}},{"LM_OPCAN_ACTV_CGC_VEST",{{"OPTRE_32Rnd_762x51_Mag",6,32}}},{"B_RadioBag_01_ghex_F",{{"OPTRE_32Rnd_762x51_Mag",8,32}}},"H_Cap_headphones","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_HesetSemi_Organized_AA_Zeus_01 : O_HesetSemi_Organized_AA_01 {
        author = "HMC. A. ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA - Zeus";
        side = 0;
        faction = "O_HesetSemi_Organized";

        identityTypes[] = {"Head_TK","LanguagePER_F","G_IRAN_default"};

        uniformClass = "OPTRE_Ins_ER_uniform_GGod";

        linkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Cap_marshal","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};
        respawnlinkedItems[] = {"LM_OPCAN_ACTV_CGC_VEST","H_Cap_marshal","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter"};

        weapons[] = {"OPTRE_BR55","TCF_M41_SSR","OPTRE_M6B","OPTRE_Binoculars"};
        respawnWeapons[] = {"OPTRE_BR55","TCF_M41_SSR","OPTRE_M6B","OPTRE_Binoculars"};

        magazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_M41_Twin_HEAT","OPTRE_8Rnd_127x40_Mag","OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag"};
        respawnMagazines[] = {"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_M41_Twin_HEAT","OPTRE_8Rnd_127x40_Mag","OPTRE_36Rnd_95x40_Mag_Tracer_Yellow","OPTRE_8Rnd_127x40_Mag"};

        backpack = "OPTRE_UNSC_Rucksack_Heavy";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_BR55","","","OPTRE_M7_Sight",{"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",36},{},""},{"TCF_M41_SSR","","","",{"OPTRE_M41_Twin_HEAT",2},{},""},{"OPTRE_M6B","","OPTRE_M6G_Flashlight","TCF_MA1B_AmmoCounter",{"OPTRE_8Rnd_127x40_Mag",8},{},""},{"OPTRE_Ins_ER_uniform_GGod",{}},{"LM_OPCAN_ACTV_CGC_VEST",{{"ACE_elasticBandage",8},{"OPTRE_36Rnd_95x40_Mag_Tracer_Yellow",12,36},{"OPTRE_M41_Twin_HEAT",1,2}}},{"OPTRE_UNSC_Rucksack_Heavy",{{"OPTRE_M41_Twin_HE_Thermal_ProximityFuse",4,2}}},"H_Cap_marshal","",{"OPTRE_Binoculars","","","",{},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};