//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 214.150957 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_AstraFederation {
        displayName = "[10th] United Astra Federation";
        side = 0;
        flag = "\Tenthed_Core\data\logo.paa";
        icon = "\Tenthed_Core\data\logo.paa";
        priority = 0;
    };
};

#include "CfgGroups.hpp"

class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_T_Soldier_SL_F;
    class O_T_Soldier_SL_F_OCimport_01 : O_T_Soldier_SL_F { scope = 0; class EventHandlers; };
    class O_T_Soldier_SL_F_OCimport_02 : O_T_Soldier_SL_F_OCimport_01 { class EventHandlers; };

    class O_Astra_Squad_Lead_01 : O_T_Soldier_SL_F_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Lead";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Security","Tenthed_Astra_CH252A_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Security","Tenthed_Astra_CH252A_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T51_Repeater","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T51_Repeater","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Heavy_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T51_Repeater","","","",{"OPTRE_FC_T51_Repeater_Battery",400},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T51_Repeater_Battery",2,400}}},{"Tenthed_Astra_Security",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T51_Repeater_Battery",1,400}}},{"Tenthed_Marine_Heavy_Rucksack",{{"OPTRE_FC_T51_Repeater_Battery",8,400}}},"Tenthed_Astra_CH252A_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Medic_01 : O_Astra_Squad_Lead_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Corpsman","Tenthed_Astra_CH252_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Corpsman","Tenthed_Astra_CH252_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M12_SOC","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M12_SOC","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_64Rnd_57x31_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_64Rnd_57x31_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_64Rnd_57x31_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_64Rnd_57x31_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Medical_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M12_SOC","","OPTRE_M45_Flashlight","OPTRE_M12_Optic",{"OPTRE_64Rnd_57x31_Mag",64},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"ACE_surgicalKit",1},{"OPTRE_64Rnd_57x31_Mag",10,64}}},{"Tenthed_Astra_Corpsman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{"Tenthed_Marine_Medical_Rucksack",{{"ACE_bloodIV_500",10},{"ACE_bloodIV_250",10},{"ACE_bloodIV",10},{"ACE_morphine",10},{"ACE_splint",10},{"ACE_epinephrine",10}}},"Tenthed_Astra_CH252_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Riflemen_01 : O_Astra_Squad_Lead_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Riflemen";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25_Rifle","","","",{"OPTRE_FC_T25_Rifle_Battery",250},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T25_Rifle_Battery",10,250}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Riflemen_02 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Riflemen - Assault RIfle";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5A","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_MA5A","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5A","","TCF_MA1B_Flashlight","TCF_MA1B_AmmoCounter",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_32Rnd_762x51_Mag",3,32}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_32Rnd_762x51_Mag",20,32},{"OPTRE_32Rnd_762x51_Mag_Tracer",10,32}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Riflemen_03 : O_Astra_Riflemen_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Riflemen - Assault Rifle W/AT";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5A","TCF_M96_LAW_Blk","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_MA5A","TCF_M96_LAW_Blk","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","TCF_M96_HEAT","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","TCF_M96_HEAT","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5A","","TCF_MA1B_Flashlight","TCF_MA1B_AmmoCounter",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"TCF_M96_LAW_Blk","","","",{"TCF_M96_HEAT",1},{},""},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_32Rnd_762x51_Mag",3,32}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"TCF_M96_HEAT",2,1}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_32Rnd_762x51_Mag",20,32},{"OPTRE_32Rnd_762x51_Mag_Tracer",10,32}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Riflemen_04 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Riflemen - W/AT";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T25_Rifle","TCF_M96_LAW_Blk","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T25_Rifle","TCF_M96_LAW_Blk","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T25_Rifle_Battery","TCF_M96_HEAT","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T25_Rifle_Battery","TCF_M96_HEAT","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25_Rifle","","","",{"OPTRE_FC_T25_Rifle_Battery",250},{},""},{"TCF_M96_LAW_Blk","","","",{"TCF_M96_HEAT",1},{},""},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T25_Rifle_Battery",10,250}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Shield_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Shield";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_Jackal_Shield","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_Jackal_Shield","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_Jackal_Shield","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_Plasma_Pistol_Battery",3,300}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",10,300}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_Plasma_Pistol_Battery",8,300}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Heavy_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M247H_Etilka","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M247H_Etilka","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M247H_Etilka","","","",{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",200},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",3,200}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Heavy_02 : O_Astra_Heavy_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy - Shield";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M247H_Shield_Etilka","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M247H_Shield_Etilka","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M247H_Shield_Etilka","","","",{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",200},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Anti_Air_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Anti-Air";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_T33_FuelRod_Cannon_Guided","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_T33_FuelRod_Cannon_Guided","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack_Guided","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack_Guided","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Heavy_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25_Rifle","","","",{"OPTRE_FC_T25_Rifle_Battery",250},{},""},{"OPTRE_FC_T33_FuelRod_Cannon_Guided","","","",{"OPTRE_FC_T33_FuelRod_Pack_Guided",5},{},""},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Marine_Heavy_Rucksack",{{"OPTRE_FC_T25_Rifle_Battery",6,250},{"OPTRE_FC_T33_FuelRod_Pack_Guided",4,5}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Anti_Tank_01 : O_Astra_Anti_Air_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Anti-Tank";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_T33_FuelRod_Cannon","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_T33_FuelRod_Cannon","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Heavy_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25_Rifle","","","",{"OPTRE_FC_T25_Rifle_Battery",250},{},""},{"OPTRE_FC_T33_FuelRod_Cannon","","","",{"OPTRE_FC_T33_FuelRod_Pack",5},{},""},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Marine_Heavy_Rucksack",{{"OPTRE_FC_T25_Rifle_Battery",6,250},{"OPTRE_FC_T33_FuelRod_Pack",4,5}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Grenadier_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Grenadier","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Grenadier","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T50_ConcussionRifle","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T50_ConcussionRifle","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T50_6rnd_mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T50_6rnd_mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T50_6rnd_mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T50_6rnd_mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T50_ConcussionRifle","","","",{"OPTRE_FC_T50_6rnd_mag",6},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T50_6rnd_mag",2,6}}},{"Tenthed_Astra_Grenadier",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T50_6rnd_mag",1,6}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T50_6rnd_mag",5,6}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Grenadier_02 : O_Astra_Grenadier_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier Rotery";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Grenadier","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Grenadier","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"MA_GRL_45","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"MA_GRL_45","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"GRL45_6rnd_HE","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","GRL45_6rnd_HE","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"GRL45_6rnd_HE","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","GRL45_6rnd_HE","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"MA_GRL_45","","","",{"GRL45_6rnd_HE",6},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{}},{"Tenthed_Astra_Grenadier",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{"Tenthed_Marine_Rucksack",{{"GRL45_6rnd_HE",3,6},{"GRL45_6rnd_Whistle",2,6},{"GRL45_6rnd_Flare_Red",3,6}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Marksmen_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksmen";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_Recon_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_Recon_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T51_Carbine","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T51_Carbine","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T51_Ammo_Cartridge","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T51_Ammo_Cartridge","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T51_Ammo_Cartridge","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T51_Ammo_Cartridge","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T51_Carbine","","","",{"OPTRE_FC_T51_Ammo_Cartridge",18},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T51_Ammo_Cartridge",3,18}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T51_Ammo_Cartridge",20,18}}},"Tenthed_Astra_Recon_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Sniper_01 : O_Astra_Marksmen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_Recon_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_Recon_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T50_SRS","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T50_SRS","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T50_SRS_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T50_SRS_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T50_SRS_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T50_SRS_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T50_SRS","","","",{"OPTRE_FC_T50_SRS_Battery",10},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T50_SRS_Battery",3,10}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T50_SRS_Battery",10,10}}},"Tenthed_Astra_Recon_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_VIP_01 : O_Astra_Squad_Lead_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "VIP";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_NATO","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "OPTRE_UNSC_Dress_Uniform_gray";

        linkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"OPTRE_UNSC_Dress_Uniform_gray",{}},{},{},"","G_Aviator",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_VIP_02 : O_Astra_VIP_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "VIP";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_NATO","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "OPTRE_UNSC_Dress_Uniform_gray";

        linkedItems[] = {"Frieden_Grey_beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Frieden_Grey_beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"OPTRE_UNSC_Dress_Uniform_gray",{}},{},{},"Frieden_Grey_beret","G_Aviator",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Engineer_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_CH252A_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_CH252A_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M45ATAC","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M45ATAC","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Heavy_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45ATAC","","TCF_MA1B_Flashlight","OPTRE_M7_Sight",{"OPTRE_6Rnd_8Gauge_Pellets",6},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"ACE_DeadManSwitch",1},{"ACE_DefusalKit",1},{"ACE_Fortify",1},{"ACE_EntrenchingTool",1},{"ACE_Clacker",1},{"ToolKit",1}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",2,300},{"OPTRE_6Rnd_8Gauge_Pellets",17,6}}},{"Tenthed_Marine_Heavy_Rucksack",{{"APERSMineDispenser_Mag",2,1},{"ATMine_Range_Mag",2,1},{"ACE_FlareTripMine_Mag",1,1},{"APERSMine_Range_Mag",3,1},{"APERSBoundingMine_Range_Mag",1,1},{"C7_Remote_Mag",1,1},{"APERSTripMine_Wire_Mag",1,1},{"OPTRE_FC_BubbleShield",1,1}}},"Tenthed_Astra_CH252A_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_VIP_03 : O_Astra_VIP_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "VIP";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_NATO","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "U_B_ParadeUniform_01_US_decorated_F";

        linkedItems[] = {"Frieden_Grey_beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Frieden_Grey_beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"U_B_ParadeUniform_01_US_decorated_F",{}},{},{},"Frieden_Grey_beret","G_Aviator",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Crewmen_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewmen";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Security","OPTRE_UNSC_VX16_HelmetV","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Security","OPTRE_UNSC_VX16_HelmetV","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M7","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","OPTRE_M45_Flashlight","OPTRE_M7_Sight",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_60Rnd_5x23mm_Mag",3,60}}},{"Tenthed_Astra_Security",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{},"OPTRE_UNSC_VX16_HelmetV","",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

};