//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 214.150957 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_AstraFederation {
        displayName = "[10th] United Astra Federation";
        side = 0;
        flag = "\Tenthed_Core\data\logo.paa";
        icon = "\Tenthed_Core\data\logo.paa";
        priority = 0;
    };
};

class CfgGroups {
    class EAST {

        class O_AstraFederation {
            name = "[10th] United Astra Federation";

            class Infantry {
                name = "Infantry";

                class o_Astra_infantry_riflemen_squad_02 {
                    name = "Riflemen Squad 2";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_04";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_01";
                    };
                };

                class o_Astra_infantry_riflemen_squad_01 {
                    name = "Riflemen Squad 1";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                    class Unit2 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_02";
                    };
                    class Unit3 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_03";
                    };
                    class Unit4 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_02";
                    };
                    class Unit5 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_02";
                    };
                };

                class o_Astra_infantry_medic_squad {
                    name = "Medic Squad";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                };

                class o_Astra_infantry_riflemen_squad_03 {
                    name = "Riflemen Squad 3";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_04";
                    };
                    class Unit3 {
                        position[] = {5,-15,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Riflemen_03";
                    };
                    class Unit4 {
                        position[] = {10,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Shield_01";
                    };
                    class Unit5 {
                        position[] = {-10,-20,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Shield_01";
                    };
                };

                class o_Astra_infantry_heavy_machine_gun_squad {
                    name = "Heavy Machine gun squad";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Heavy_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Heavy_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Heavy_02";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                };

                class o_Astra_infantry_engineer_squad {
                    name = "Engineer Squad";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Engineer_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Engineer_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Engineer_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                };

                class o_Astra_infantry_anti_tank_squad {
                    name = "Anti-Tank Squad";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Anti_Tank_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Anti_Tank_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                };

                class o_Astra_infantry_anti_air_squad {
                    name = "Anti-Air Squad";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Anti_Air_01";
                    };
                    class Unit2 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Anti_Air_01";
                    };
                    class Unit3 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                };

                class o_Astra_infantry_grenadier_squad_02 {
                    name = "Grenadier Squad 2";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Grenadier_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Grenadier_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                };

                class o_Astra_infantry_grenadier_squad_01 {
                    name = "Grenadier Squad 1";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Grenadier_02";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Grenadier_02";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                };

                class o_Astra_infantry_shield_squad {
                    name = "Shield Squad";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Shield_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Shield_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Shield_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                };

                class o_Astra_infantry_crewmen_squad {
                    name = "Crewmen Squad";
                    side = 0;
                    faction = "O_AstraFederation";
                    icon = "\A3\ui_f\data\map\markers\nato\o_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 0;
                        vehicle = "O_Astra_Squad_Lead_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "CORPORAL";
                        side = 0;
                        vehicle = "O_Astra_Medic_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Crewmen_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Crewmen_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "PRIVATE";
                        side = 0;
                        vehicle = "O_Astra_Crewmen_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class O_T_Soldier_SL_F;
    class O_T_Soldier_SL_F_OCimport_01 : O_T_Soldier_SL_F { scope = 0; class EventHandlers; };
    class O_T_Soldier_SL_F_OCimport_02 : O_T_Soldier_SL_F_OCimport_01 { class EventHandlers; };

    class Tenthed_OPTRE_Pelican_unarmed_ins;
    class Tenthed_OPTRE_Pelican_unarmed_ins_OCimport_01 : Tenthed_OPTRE_Pelican_unarmed_ins { scope = 0; class EventHandlers; class Turrets; };
    class Tenthed_OPTRE_Pelican_unarmed_ins_OCimport_02 : Tenthed_OPTRE_Pelican_unarmed_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class OPTRE_FC_Type26B_Banshee;
    class OPTRE_FC_Type26B_Banshee_OCimport_01 : OPTRE_FC_Type26B_Banshee { scope = 0; class EventHandlers; };
    class OPTRE_FC_Type26B_Banshee_OCimport_02 : OPTRE_FC_Type26B_Banshee_OCimport_01 { scope = 0; class EventHandlers; };

    class OPTRE_FC_SAM_Wraith_Needle;
    class OPTRE_FC_SAM_Wraith_Needle_OCimport_01 : OPTRE_FC_SAM_Wraith_Needle { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_SAM_Wraith_Needle_OCimport_02 : OPTRE_FC_SAM_Wraith_Needle_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_FC_Ghost;
    class OPTRE_FC_Ghost_OCimport_01 : OPTRE_FC_Ghost { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_Ghost_OCimport_02 : OPTRE_FC_Ghost_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_FC_Wraith;
    class OPTRE_FC_Wraith_OCimport_01 : OPTRE_FC_Wraith { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_Wraith_OCimport_02 : OPTRE_FC_Wraith_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_FC_Wraith_Tank;
    class OPTRE_FC_Wraith_Tank_OCimport_01 : OPTRE_FC_Wraith_Tank { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_Wraith_Tank_OCimport_02 : OPTRE_FC_Wraith_Tank_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class Tenthed_OPTRE_M12_LRV_ins;
    class Tenthed_OPTRE_M12_LRV_ins_OCimport_01 : Tenthed_OPTRE_M12_LRV_ins { scope = 0; class EventHandlers; class Turrets; };
    class Tenthed_OPTRE_M12_LRV_ins_OCimport_02 : Tenthed_OPTRE_M12_LRV_ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoGunner_1;
            class MainTurret;
        };
    };

    class Tenthed_OPTRE_Static_M41_Ins;
    class Tenthed_OPTRE_Static_M41_Ins_OCimport_01 : Tenthed_OPTRE_Static_M41_Ins { scope = 0; class EventHandlers; class Turrets; };
    class Tenthed_OPTRE_Static_M41_Ins_OCimport_02 : Tenthed_OPTRE_Static_M41_Ins_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_FC_T26_AI;
    class OPTRE_FC_T26_AI_OCimport_01 : OPTRE_FC_T26_AI { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_T26_AI_OCimport_02 : OPTRE_FC_T26_AI_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_FC_T26_AT;
    class OPTRE_FC_T26_AT_OCimport_01 : OPTRE_FC_T26_AT { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_T26_AT_OCimport_02 : OPTRE_FC_T26_AT_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class OPTRE_FC_T26_AA;
    class OPTRE_FC_T26_AA_OCimport_01 : OPTRE_FC_T26_AA { scope = 0; class EventHandlers; class Turrets; };
    class OPTRE_FC_T26_AA_OCimport_02 : OPTRE_FC_T26_AA_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class Tenthed_OPTRE_ins_falcon;
    class Tenthed_OPTRE_ins_falcon_OCimport_01 : Tenthed_OPTRE_ins_falcon { scope = 0; class EventHandlers; class Turrets; };
    class Tenthed_OPTRE_ins_falcon_OCimport_02 : Tenthed_OPTRE_ins_falcon_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class LeftDoorGun;
            class RightDoorGun;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
        };
    };


    class O_Astra_Squad_Lead_01 : O_T_Soldier_SL_F_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Lead";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Security","Tenthed_Astra_CH252A_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Security","Tenthed_Astra_CH252A_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T51_Repeater","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T51_Repeater","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T51_Repeater_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Heavy_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T51_Repeater","","","",{"OPTRE_FC_T51_Repeater_Battery",400},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T51_Repeater_Battery",2,400}}},{"Tenthed_Astra_Security",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T51_Repeater_Battery",1,400}}},{"Tenthed_Marine_Heavy_Rucksack",{{"OPTRE_FC_T51_Repeater_Battery",8,400}}},"Tenthed_Astra_CH252A_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Medic_01 : O_Astra_Squad_Lead_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Corpsman","Tenthed_Astra_CH252_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Corpsman","Tenthed_Astra_CH252_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M12_SOC","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M12_SOC","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_64Rnd_57x31_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_64Rnd_57x31_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_64Rnd_57x31_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_64Rnd_57x31_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Medical_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M12_SOC","","OPTRE_M45_Flashlight","OPTRE_M12_Optic",{"OPTRE_64Rnd_57x31_Mag",64},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"ACE_surgicalKit",1},{"OPTRE_64Rnd_57x31_Mag",10,64}}},{"Tenthed_Astra_Corpsman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{"Tenthed_Marine_Medical_Rucksack",{{"ACE_bloodIV_500",10},{"ACE_bloodIV_250",10},{"ACE_bloodIV",10},{"ACE_morphine",10},{"ACE_splint",10},{"ACE_epinephrine",10}}},"Tenthed_Astra_CH252_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Riflemen_01 : O_Astra_Squad_Lead_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Riflemen";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25_Rifle","","","",{"OPTRE_FC_T25_Rifle_Battery",250},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T25_Rifle_Battery",10,250}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Riflemen_02 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Riflemen - Assault RIfle";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5A","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_MA5A","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5A","","TCF_MA1B_Flashlight","TCF_MA1B_AmmoCounter",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_32Rnd_762x51_Mag",3,32}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_32Rnd_762x51_Mag",20,32},{"OPTRE_32Rnd_762x51_Mag_Tracer",10,32}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Riflemen_03 : O_Astra_Riflemen_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Riflemen - Assault Rifle W/AT";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_MA5A","TCF_M96_LAW_Blk","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_MA5A","TCF_M96_LAW_Blk","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","TCF_M96_HEAT","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","TCF_M96_HEAT","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_32Rnd_762x51_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA5A","","TCF_MA1B_Flashlight","TCF_MA1B_AmmoCounter",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{"TCF_M96_LAW_Blk","","","",{"TCF_M96_HEAT",1},{},""},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_32Rnd_762x51_Mag",3,32}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"TCF_M96_HEAT",2,1}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_32Rnd_762x51_Mag",20,32},{"OPTRE_32Rnd_762x51_Mag_Tracer",10,32}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Riflemen_04 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Riflemen - W/AT";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T25_Rifle","TCF_M96_LAW_Blk","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T25_Rifle","TCF_M96_LAW_Blk","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T25_Rifle_Battery","TCF_M96_HEAT","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T25_Rifle_Battery","TCF_M96_HEAT","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25_Rifle","","","",{"OPTRE_FC_T25_Rifle_Battery",250},{},""},{"TCF_M96_LAW_Blk","","","",{"TCF_M96_HEAT",1},{},""},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T25_Rifle_Battery",10,250}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Shield_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Shield";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_Jackal_Shield","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_Jackal_Shield","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_Jackal_Shield","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_Plasma_Pistol_Battery",3,300}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",10,300}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_Plasma_Pistol_Battery",8,300}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Heavy_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M247H_Etilka","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M247H_Etilka","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M247H_Etilka","","","",{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",200},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",3,200}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Heavy_02 : O_Astra_Heavy_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Heavy - Shield";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M247H_Shield_Etilka","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M247H_Shield_Etilka","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_200Rnd_127x99_M247H_Etilka_Ball","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M247H_Shield_Etilka","","","",{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",200},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_200Rnd_127x99_M247H_Etilka_Ball",1,200}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Anti_Air_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Anti-Air";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_T33_FuelRod_Cannon_Guided","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_T33_FuelRod_Cannon_Guided","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack_Guided","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack_Guided","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Heavy_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25_Rifle","","","",{"OPTRE_FC_T25_Rifle_Battery",250},{},""},{"OPTRE_FC_T33_FuelRod_Cannon_Guided","","","",{"OPTRE_FC_T33_FuelRod_Pack_Guided",5},{},""},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Marine_Heavy_Rucksack",{{"OPTRE_FC_T25_Rifle_Battery",6,250},{"OPTRE_FC_T33_FuelRod_Pack_Guided",4,5}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Anti_Tank_01 : O_Astra_Anti_Air_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Anti-Tank";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_T33_FuelRod_Cannon","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T25_Rifle","OPTRE_FC_T33_FuelRod_Cannon","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_T33_FuelRod_Pack","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T25_Rifle_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Heavy_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T25_Rifle","","","",{"OPTRE_FC_T25_Rifle_Battery",250},{},""},{"OPTRE_FC_T33_FuelRod_Cannon","","","",{"OPTRE_FC_T33_FuelRod_Pack",5},{},""},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T25_Rifle_Battery",3,250}}},{"Tenthed_Marine_Heavy_Rucksack",{{"OPTRE_FC_T25_Rifle_Battery",6,250},{"OPTRE_FC_T33_FuelRod_Pack",4,5}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Grenadier_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Grenadier","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Grenadier","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T50_ConcussionRifle","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T50_ConcussionRifle","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T50_6rnd_mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T50_6rnd_mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T50_6rnd_mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T50_6rnd_mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T50_ConcussionRifle","","","",{"OPTRE_FC_T50_6rnd_mag",6},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T50_6rnd_mag",2,6}}},{"Tenthed_Astra_Grenadier",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300},{"OPTRE_FC_T50_6rnd_mag",1,6}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T50_6rnd_mag",5,6}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Grenadier_02 : O_Astra_Grenadier_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Grenadier Rotery";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Grenadier","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Grenadier","Tenthed_Astra_VX19_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"MA_GRL_45","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"MA_GRL_45","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"GRL45_6rnd_HE","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","GRL45_6rnd_HE","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"GRL45_6rnd_HE","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","GRL45_6rnd_HE","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"MA_GRL_45","","","",{"GRL45_6rnd_HE",6},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{}},{"Tenthed_Astra_Grenadier",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{"Tenthed_Marine_Rucksack",{{"GRL45_6rnd_HE",3,6},{"GRL45_6rnd_Whistle",2,6},{"GRL45_6rnd_Flare_Red",3,6}}},"Tenthed_Astra_VX19_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Marksmen_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksmen";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_Recon_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_Recon_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T51_Carbine","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T51_Carbine","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T51_Ammo_Cartridge","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T51_Ammo_Cartridge","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T51_Ammo_Cartridge","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T51_Ammo_Cartridge","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T51_Carbine","","","",{"OPTRE_FC_T51_Ammo_Cartridge",18},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T51_Ammo_Cartridge",3,18}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T51_Ammo_Cartridge",20,18}}},"Tenthed_Astra_Recon_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Sniper_01 : O_Astra_Marksmen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_Recon_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_Recon_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_T50_SRS","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_T50_SRS","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_T50_SRS_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T50_SRS_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_T50_SRS_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_T50_SRS_Battery","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_FC_T50_SRS","","","",{"OPTRE_FC_T50_SRS_Battery",10},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_FC_T50_SRS_Battery",3,10}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1}}},{"Tenthed_Marine_Rucksack",{{"OPTRE_FC_T50_SRS_Battery",10,10}}},"Tenthed_Astra_Recon_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_VIP_01 : O_Astra_Squad_Lead_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "VIP";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_NATO","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "OPTRE_UNSC_Dress_Uniform_gray";

        linkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"OPTRE_UNSC_Dress_Uniform_gray",{}},{},{},"","G_Aviator",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_VIP_02 : O_Astra_VIP_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "VIP";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_NATO","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "OPTRE_UNSC_Dress_Uniform_gray";

        linkedItems[] = {"Frieden_Grey_beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Frieden_Grey_beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"OPTRE_UNSC_Dress_Uniform_gray",{}},{},{},"Frieden_Grey_beret","G_Aviator",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Engineer_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Engineer";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_CH252A_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Rifleman","Tenthed_Astra_CH252A_Helmet","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M45ATAC","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M45ATAC","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_6Rnd_8Gauge_Pellets","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_6Rnd_8Gauge_Pellets","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        backpack = "Tenthed_Marine_Heavy_Rucksack";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45ATAC","","TCF_MA1B_Flashlight","OPTRE_M7_Sight",{"OPTRE_6Rnd_8Gauge_Pellets",6},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"ACE_DeadManSwitch",1},{"ACE_DefusalKit",1},{"ACE_Fortify",1},{"ACE_EntrenchingTool",1},{"ACE_Clacker",1},{"ToolKit",1}}},{"Tenthed_Astra_Rifleman",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",2,300},{"OPTRE_6Rnd_8Gauge_Pellets",17,6}}},{"Tenthed_Marine_Heavy_Rucksack",{{"APERSMineDispenser_Mag",2,1},{"ATMine_Range_Mag",2,1},{"ACE_FlareTripMine_Mag",1,1},{"APERSMine_Range_Mag",3,1},{"APERSBoundingMine_Range_Mag",1,1},{"C7_Remote_Mag",1,1},{"APERSTripMine_Wire_Mag",1,1},{"OPTRE_FC_BubbleShield",1,1}}},"Tenthed_Astra_CH252A_Helmet","G_Balaclava_blk",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_VIP_03 : O_Astra_VIP_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "VIP";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_NATO","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "U_B_ParadeUniform_01_US_decorated_F";

        linkedItems[] = {"Frieden_Grey_beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Frieden_Grey_beret","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"U_B_ParadeUniform_01_US_decorated_F",{}},{},{},"Frieden_Grey_beret","G_Aviator",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Crewmen_01 : O_Astra_Riflemen_01 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crewmen";
        side = 0;
        faction = "O_AstraFederation";

        identityTypes[] = {"Head_Asian","LanguageCHI_F","G_CIVIL_male"};

        uniformClass = "VES_BDU_Evolved_Slim";

        linkedItems[] = {"Tenthed_Astra_Security","OPTRE_UNSC_VX16_HelmetV","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};
        respawnlinkedItems[] = {"Tenthed_Astra_Security","OPTRE_UNSC_VX16_HelmetV","ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"};

        weapons[] = {"OPTRE_M7","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};
        respawnWeapons[] = {"OPTRE_M7","OPTRE_FC_Plasma_Pistol","OPTRE_Smartfinder"};

        magazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_60Rnd_5x23mm_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries","OPTRE_60Rnd_5x23mm_Mag","OPTRE_FC_Plasma_Pistol_Battery","Laserbatteries"};

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M7","","OPTRE_M45_Flashlight","OPTRE_M7_Sight",{"OPTRE_60Rnd_5x23mm_Mag",60},{},""},{},{"OPTRE_FC_Plasma_Pistol","","","",{"OPTRE_FC_Plasma_Pistol_Battery",300},{},""},{"VES_BDU_Evolved_Slim",{{"OPTRE_60Rnd_5x23mm_Mag",3,60}}},{"Tenthed_Astra_Security",{{"OPTRE_Biofoam",4},{"ACE_fieldDressing",10},{"ACE_Banana",1},{"OPTRE_FC_Plasma_Pistol_Battery",5,300}}},{},"OPTRE_UNSC_VX16_HelmetV","",{"OPTRE_Smartfinder","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ACE_Altimeter","OPTRE_NVG"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Pelican_01 : Tenthed_OPTRE_Pelican_unarmed_ins_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pelican";
        side = 0;
        faction = "O_AstraFederation";
        crew = "O_Astra_Crewmen_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "O_Astra_Crewmen_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_Astra_Crewmen_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_Astra_Crewmen_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_Vehicles\Pelican\data\PelicanExterior_innie_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "colorinnie";

    };

    class O_Astra_Banshee_01 : OPTRE_FC_Type26B_Banshee_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Banshee";
        side = 0;
        faction = "O_AstraFederation";
        crew = "O_Astra_Crewmen_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_AA_Wraith_01 : OPTRE_FC_SAM_Wraith_Needle_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "AA Wraith";
        side = 0;
        faction = "O_AstraFederation";
        crew = "O_Astra_Crewmen_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_Astra_Crewmen_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_body_co.paa'];_unit setObjectTextureGlobal [1,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_wings_co.paa'];_unit setObjectTextureGlobal [2,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_trail_co.paa'];_unit setObjectTextureGlobal [3,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_mortar_co.paa'];_unit setObjectTextureGlobal [4,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_cage_n_gunner_co.paa'];_unit setObjectTextureGlobal [5,'OPTRE_FC_Vehicles\Wraith\data\Mortar\wraith_smg_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Base";

    };

    class O_Astra_Ghost_01 : OPTRE_FC_Ghost_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ghost";
        side = 0;
        faction = "O_AstraFederation";
        crew = "O_Astra_Crewmen_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Wraith_01 : OPTRE_FC_Wraith_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wraith";
        side = 0;
        faction = "O_AstraFederation";
        crew = "O_Astra_Crewmen_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_Astra_Crewmen_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Wraith_Tank_01 : OPTRE_FC_Wraith_Tank_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Wraith Tank";
        side = 0;
        faction = "O_AstraFederation";
        crew = "O_Astra_Crewmen_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_Astra_Crewmen_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_LAAG_Warthog_01 : Tenthed_OPTRE_M12_LRV_ins_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "LAAG Warthog";
        side = 0;
        faction = "O_AstraFederation";
        crew = "O_Astra_Squad_Lead_01";

        class Turrets : Turrets {
            class CargoGunner_1 : CargoGunner_1 { gunnerType = "O_Astra_Riflemen_01"; };
            class MainTurret : MainTurret { gunnerType = "O_Astra_Riflemen_02"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_LAAG_Turret_01 : Tenthed_OPTRE_Static_M41_Ins_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "LAAG Turret";
        side = 0;
        faction = "O_AstraFederation";
        crew = "OPTRE_Ins_URF_Rifleman_AR";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_Astra_Riflemen_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Shade_Turret_01 : OPTRE_FC_T26_AI_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Shade Anti-Infantry Turret";
        side = 0;
        faction = "O_AstraFederation";
        crew = "OPTRE_FC_Elite_Minor";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_Astra_Engineer_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Shade_Turret_02 : OPTRE_FC_T26_AT_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Shade Anti-Tank Turret";
        side = 0;
        faction = "O_AstraFederation";
        crew = "OPTRE_FC_Elite_Minor";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_Astra_Engineer_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Shade_Turret_03 : OPTRE_FC_T26_AA_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Shade AA Turret";
        side = 0;
        faction = "O_AstraFederation";
        crew = "OPTRE_FC_Elite_Minor";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_Astra_Crewmen_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_Astra_Falcon_01 : Tenthed_OPTRE_ins_falcon_OCimport_02 {
        author = "2ndLt ""Akira"" Sullivan";
        scope = 2;
        scopeCurator = 2;
        displayName = "Falcon - Armed";
        side = 0;
        faction = "O_AstraFederation";
        crew = "O_Astra_Crewmen_01";

        class Turrets : Turrets {
            class LeftDoorGun : LeftDoorGun { gunnerType = "O_Astra_Crewmen_01"; };
            class RightDoorGun : RightDoorGun { gunnerType = "O_Astra_Crewmen_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_Astra_Riflemen_02"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_Astra_Riflemen_02"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "O_Astra_Riflemen_01"; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = "O_Astra_Riflemen_03"; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = "O_Astra_Riflemen_04"; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = "O_Astra_Riflemen_01"; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = "O_Astra_Riflemen_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\OPTRE_Vehicles_Air\Falcon\data\Innie\Innie_Falcon_Main_co.paa'];_unit setObjectTextureGlobal [1,'\OPTRE_Vehicles_Air\Falcon\data\Innie\Innie_Falcon_Attachments_co.paa'];_unit setObjectTextureGlobal [2,'\OPTRE_Vehicles_Air\Falcon\data\Innie\Innie_Falcon_Interior_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Innie";

    };

};